# -*- coding: utf-8 -*-
"""SimpleWebScraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdVPFZmtWFwe3HwwInzQGBdEUPh_GMmT
"""

# Import libraries
import os   # os library helps interact with the os- create folders and work with files on computer
import requests   # requests is the standard library for making HTTP requests- vist website using url, retrieves resource/data or perform an action
from bs4 import BeautifulSoup  #importing BeautifulSoup 4 library- bs4 package library and BeautifulSoup is the package
from google.colab import drive

#Mount Google Drive
drive.mount('/content/drive')

# Input: Medium article URL
url = input("Enter Medium article URL:")

# Send request to the URL
response = requests.get(url)   #downloads the webpage and stores it in response

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")    #the website content in response.text is given to BeautifulSoup for parsing and stored in variable soup

# Extract all text from the page
article_text = soup.get_text()

# Create folder named 'scraped_articles' if it does not exist
folder_name = "/content/drive/MyDrive/scraped_articles"
os.makedirs(folder_name, exist_ok=True)


# File path
file_path = os.path.join(folder_name, "article.txt")

# Save text to a .txt file
with open(file_path, "w", encoding="utf-8") as file:
    file.write(article_text)

print("Article successfully scraped and saved!")
print("Saved at:", file_path)